[2024-01-20T02:23:51.015+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bancodedados.insert_data manual__2024-01-20T02:23:48.546800+00:00 [queued]>
[2024-01-20T02:23:51.020+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bancodedados.insert_data manual__2024-01-20T02:23:48.546800+00:00 [queued]>
[2024-01-20T02:23:51.020+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-20T02:23:51.020+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-01-20T02:23:51.020+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-20T02:23:51.026+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): insert_data> on 2024-01-20 02:23:48.546800+00:00
[2024-01-20T02:23:51.029+0000] {standard_task_runner.py:55} INFO - Started process 49795 to run task
[2024-01-20T02:23:51.033+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'bancodedados', 'insert_data', 'manual__2024-01-20T02:23:48.546800+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/23-bancodedados.py', '--cfg-path', '/tmp/tmp6u849htf']
[2024-01-20T02:23:51.033+0000] {standard_task_runner.py:83} INFO - Job 134: Subtask insert_data
[2024-01-20T02:23:51.083+0000] {task_command.py:388} INFO - Running <TaskInstance: bancodedados.insert_data manual__2024-01-20T02:23:48.546800+00:00 [running]> on host cb9489d15b76
[2024-01-20T02:23:51.116+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bancodedados
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2024-01-20T02:23:48.546800+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-20T02:23:48.546800+00:00
[2024-01-20T02:23:51.116+0000] {sql.py:254} INFO - Executing: insert into teste values(1);
[2024-01-20T02:23:51.120+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2024-01-20T02:23:51.208+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2024-01-20T02:23:51.210+0000] {sql.py:375} INFO - Running statement: insert into teste values(1);, parameters: None
[2024-01-20T02:23:51.211+0000] {sql.py:384} INFO - Rows affected: 1
[2024-01-20T02:23:51.216+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=bancodedados, task_id=insert_data, execution_date=20240120T022348, start_date=20240120T022351, end_date=20240120T022351
[2024-01-20T02:23:51.253+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-01-20T02:23:51.285+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
