[2024-01-09T20:26:35.188+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdagallfailed.tsk3 manual__2024-01-09T20:26:32.815967+00:00 [queued]>
[2024-01-09T20:26:35.193+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdagallfailed.tsk3 manual__2024-01-09T20:26:32.815967+00:00 [queued]>
[2024-01-09T20:26:35.193+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-09T20:26:35.194+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-01-09T20:26:35.194+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-09T20:26:35.201+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk3> on 2024-01-09 20:26:32.815967+00:00
[2024-01-09T20:26:35.204+0000] {standard_task_runner.py:55} INFO - Started process 47448 to run task
[2024-01-09T20:26:35.206+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'triggerdagallfailed', 'tsk3', 'manual__2024-01-09T20:26:32.815967+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/7-trigger-dag.py', '--cfg-path', '/tmp/tmp697j6pxp']
[2024-01-09T20:26:35.206+0000] {standard_task_runner.py:83} INFO - Job 30: Subtask tsk3
[2024-01-09T20:26:35.237+0000] {task_command.py:388} INFO - Running <TaskInstance: triggerdagallfailed.tsk3 manual__2024-01-09T20:26:32.815967+00:00 [running]> on host 8c81727a976c
[2024-01-09T20:26:35.282+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=triggerdagallfailed
AIRFLOW_CTX_TASK_ID=tsk3
AIRFLOW_CTX_EXECUTION_DATE=2024-01-09T20:26:32.815967+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-09T20:26:32.815967+00:00
[2024-01-09T20:26:35.283+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-09T20:26:35.283+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sleep 5']
[2024-01-09T20:26:35.289+0000] {subprocess.py:86} INFO - Output:
[2024-01-09T20:26:40.293+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-01-09T20:26:40.324+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=triggerdagallfailed, task_id=tsk3, execution_date=20240109T202632, start_date=20240109T202635, end_date=20240109T202640
[2024-01-09T20:26:40.388+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-01-09T20:26:40.400+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
