[2024-01-09T20:24:02.485+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdagfailed.tsk2 manual__2024-01-09T20:24:01.793607+00:00 [queued]>
[2024-01-09T20:24:02.491+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdagfailed.tsk2 manual__2024-01-09T20:24:01.793607+00:00 [queued]>
[2024-01-09T20:24:02.491+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-09T20:24:02.492+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-01-09T20:24:02.492+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-09T20:24:02.499+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk2> on 2024-01-09 20:24:01.793607+00:00
[2024-01-09T20:24:02.502+0000] {standard_task_runner.py:55} INFO - Started process 47205 to run task
[2024-01-09T20:24:02.507+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'triggerdagfailed', 'tsk2', 'manual__2024-01-09T20:24:01.793607+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/6-trigger-dag.py', '--cfg-path', '/tmp/tmphy1bdlho']
[2024-01-09T20:24:02.507+0000] {standard_task_runner.py:83} INFO - Job 23: Subtask tsk2
[2024-01-09T20:24:02.558+0000] {task_command.py:388} INFO - Running <TaskInstance: triggerdagfailed.tsk2 manual__2024-01-09T20:24:01.793607+00:00 [running]> on host 8c81727a976c
[2024-01-09T20:24:02.603+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=triggerdagfailed
AIRFLOW_CTX_TASK_ID=tsk2
AIRFLOW_CTX_EXECUTION_DATE=2024-01-09T20:24:01.793607+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-09T20:24:01.793607+00:00
[2024-01-09T20:24:02.604+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-09T20:24:02.604+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sleep 5']
[2024-01-09T20:24:02.611+0000] {subprocess.py:86} INFO - Output:
[2024-01-09T20:24:07.617+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-01-09T20:24:07.666+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=triggerdagfailed, task_id=tsk2, execution_date=20240109T202401, start_date=20240109T202402, end_date=20240109T202407
[2024-01-09T20:24:07.684+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-01-09T20:24:07.696+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
