[2024-01-09T20:24:03.739+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdagfailed.tsk3 manual__2024-01-09T20:24:01.793607+00:00 [queued]>
[2024-01-09T20:24:03.746+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdagfailed.tsk3 manual__2024-01-09T20:24:01.793607+00:00 [queued]>
[2024-01-09T20:24:03.746+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-01-09T20:24:03.746+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-01-09T20:24:03.746+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-01-09T20:24:03.753+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk3> on 2024-01-09 20:24:01.793607+00:00
[2024-01-09T20:24:03.759+0000] {standard_task_runner.py:55} INFO - Started process 47210 to run task
[2024-01-09T20:24:03.761+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'triggerdagfailed', 'tsk3', 'manual__2024-01-09T20:24:01.793607+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/6-trigger-dag.py', '--cfg-path', '/tmp/tmphwn7l_av']
[2024-01-09T20:24:03.762+0000] {standard_task_runner.py:83} INFO - Job 25: Subtask tsk3
[2024-01-09T20:24:03.793+0000] {task_command.py:388} INFO - Running <TaskInstance: triggerdagfailed.tsk3 manual__2024-01-09T20:24:01.793607+00:00 [running]> on host 8c81727a976c
[2024-01-09T20:24:03.825+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=triggerdagfailed
AIRFLOW_CTX_TASK_ID=tsk3
AIRFLOW_CTX_EXECUTION_DATE=2024-01-09T20:24:01.793607+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-09T20:24:01.793607+00:00
[2024-01-09T20:24:03.826+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-01-09T20:24:03.827+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'sleep 5']
[2024-01-09T20:24:03.833+0000] {subprocess.py:86} INFO - Output:
[2024-01-09T20:24:08.843+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-01-09T20:24:08.878+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=triggerdagfailed, task_id=tsk3, execution_date=20240109T202401, start_date=20240109T202403, end_date=20240109T202408
[2024-01-09T20:24:08.893+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-01-09T20:24:08.903+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
